config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "home#index"
  get "diagnoses", to: "home#diagnoses"
  get "users/show/:id" => "users#show"
  resources :tips, only: [:index, :show]

  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#new_guest"
  end
  resources :posts, except: [:update, :edit] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    render :index
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    render :index
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end
end

app/views/comments/_form.html.erb
<%= stylesheet_link_tag 'posts', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="comment_form mt-4">
    <%= form_with(model: [post, comment], url: post_comments_path(@post)) do |f| %>
    <%= f.text_area :content, class: "form-control" %>
    <div class="button-group">
        <%= f.submit "送信", class: "btn comment-submit w-25 mt-3" %>
    </div>
    <% end %>
</div>

app/views/comments/_index.html.erb
  <%= stylesheet_link_tag 'posts', media: 'all', 'data-turbolinks-track': 'reload' %>
  <div class='comment-counter'>
    <%= comments.count %>件のコメント
  </div>

  <% comments.each do |comment| %>
  <div class="card mb-1">
    <div class="comment-container">
      <div class="comment-user">
        <% if comment.user.image? %>
        <img src=<%= comment.user.image %> class="comment-icon">
        <% else %>
        <%= image_tag 'profile_default2.jpg' ,class: "comment-icon" %>
        <% end %>

        <p class='text-muted pl-2 pt-1 mb-1'><%=comment.user.name%></p>
      </div>

      <div class="comment-content p-3">
        <%= comment.content %>
      </div>

      <div class='comment_destroy'>
        <% if comment.user == current_user %>
        <%= link_to post_comment_path(comment.post_id, comment.id), method: :delete,data: { confirm: '削除しますか?', remote: true } do %>
        <i class="fas fa-trash" style="color: black;"></i> 削除
        <% end %>
        <% end %>
      </div>
    </div>
    <span class="comment-date pull-right">
      <i class='fas fa-clock home-icon'></i> <%= time_ago_in_words(comment.created_at) %>前
    </span>
  </div>
  <% end %>

app/views/comments/index.js.erb
$('#comments_area').html("<%= escape_javascript(render 'index', comments: @comments, post: @post) %>")
$("textarea").val('')