config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "home#index"
  get "diagnoses", to: "home#diagnoses"
  get "users/show/:id" => "users#show"
  resources :tips, only: [:index, :show]

  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#new_guest"
  end
  resources :posts, except: [:update, :edit] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :post_id, uniqueness: { scope: :user_id }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]

  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>

  <% unless post.like_user(current_user.id).blank? %>
    <%= link_to post_like_path(post_id: post.id, id: post.likes[0].id), method: :delete, remote: true do %>
      <div class="vertical_like">
        <i class="fas fa-heart unlike-btn" ></i>
      </div>
    <% end %>
    <p><%= post.likes.count %>件のいいね</p>
  <% else %>
    <%= link_to post_likes_path(post.id), method: :post, remote: true do %>
      <div class="vertical_like">
        <i class="far fa-heart like-btn"></i>
      </div>
    <% end %>
    <p><%= post.likes.count %>件のいいね</p>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post,like: @like}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post, like: @like}) %>");