config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "home#index"
  get "diagnoses", to: "home#diagnoses"
  get "users/show/:id" => "users#show"
  resources :tips, only: [:index, :show]

  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#new_guest"
  end
  resources :posts, except: [:update, :edit] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def diagnoses; end
end

app/views/home/_reload.html.erb
<div class="text-center">
  <%= link_to "Retry!", diagnoses_path, class:"btn btn-radius-solid btn--shadow" %>
</div>

app/views/home/diagnoses.html.erb
<%= stylesheet_link_tag 'diagnoses', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class='big-bg'>
  <h2 class='page-title'>aroma finder</h2>
  <p>質問に答えてあなたにピッタリのアロマを見つけませんか？</p>
</div>

<div id="wrapper">
  <%= image_tag 'finder-bg' ,class: 'finder-bg' %>
  <ul class="questions">
    <h1 class="title text-center">Questions</h1>
    <p class="text-center">(今のご気分でお答えください)</p>

    <li class="textBox">
      <span class="text">Q1. 気分が落ち込んでいる</span>
      <label class="yes"><input class="typeC typeE" name="q01" type="radio">YES
      </label>
      <label class="no"><input class="typeA typeJ" name="q01" type="radio">NO
      </label>
    </li>

    <li class="textBox">
      <span class="text">Q2.集中力を高めたい</span>
      <label class="yes"><input class="typeD typeE" name="q02" type="radio">YES
      </label>
      <label class="no"><input class="typeB typeG" name="q02" type="radio">NO
      </label>
    </li>

    <li class="textBox">
      <span class="text">Q3. 体内時計が乱れている</span>
      <label class="yes"><input class="typeA typeB" name="q03" type="radio">YES
      </label>
      <label class="no"><input class="typeH typeD" name="q03" type="radio">NO
      </label>
    </li>

    <li class="textBox">
      <span class="text">Q4. 最近眠りが浅い</span>
      <label class="yes"><input class="typeA typeF" name="q04" type="radio">YES
      </label>
      <label class="no"><input class="typeE typeI" name="q04" type="radio">NO
      </label>
    </li>

    <li class="textBox">
      <span class="text">Q5. 日常を忘れたい気分だ</span>
      <label class="yes"><input class="typeF typeJ" name="q05" type="radio">YES
      </label>
      <label class="no"><input class="typeD typeE" name="q05" type="radio">NO
      </label>
    </li>

    <li class="textBox">
      <span class="text">Q6.お肌のトラブルがある</span>
      <label class="yes"><input class="typeC typeG" name="q06" type="radio">YES
      </label>
      <label class="no"><input class="typeA typeB" name="q06" type="radio">NO
      </label>
    </li>

    <li class="textBox">
      <span class="text">Q7. 冷え性に悩んでいる</span>
      <label class="yes"><input class="typeH typeI typeD" name="q07" type="radio">YES
      </label>
      <label class="no"><input name="q07" type="radio">NO
      </label>
    </li>

    <li class="textBox">
      <span class="text">Q8.食欲が落ち込んでいる</span>
      <label class="yes"><input class="typeB typeD" name="q08" type="radio">YES
      </label>
      <label class="no"><input name="q08" type="radio">NO
      </label>
    </li>

    <li class="textBox">
      <span class="text">Q9.理由もなくイライラする</span>
      <label class="yes"><input class="typeA typeF" name="q09" type="radio">YES
      </label>
      <label class="no"><input class="typeD typeE" name="q09" type="radio">NO
      </label>
    </li>

    <li class="textBox">
      <span class="text">Q10. 胃腸の調子が悪い</span>
      <label class="yes"><input class="typeG typeB" name="q10" type="radio">YES
      </label>
      <label class="no"><input name="q10" type="radio">NO
      </label>
    </li>

    <li class="textBox">
      <span class="text">Q11.緊張を解したい場面だ</span>
      <label class="yes"><input class="typeE typeJ" name="q11" type="radio">YES
      </label>
      <label class="no"><input class="typeH typeD" name="q11" type="radio">NO
      </label>
    </li>

    <li class="textBox">
      <span class="text">Q12.風邪はいつも喉からくる</span>
      <label class="yes"><input class="typeH typeI" name="q12" type="radio">YES
      </label>
      <label class="no"><input name="q12" type="radio">NO
      </label>
    </li>

    <li class="textBox">
      <span class="text">Q13. 仕事のことが忘れられない</span>
      <label class="yes"><input class="typeF typeJ" name="q13" type="radio">YES
      </label>
      <label class="no"><input class="typeA typeC" name="q13" type="radio">NO
      </label>
    </li>

    <li class="textBox">
      <span class="text">Q14.足のむくみが気になる</span>
      <label class="yes"><input class="typeD typeH typeI" name="q14" type="radio">YES
      </label>
      <label class="no"><input name="q14" type="radio">NO
      </label>
    </li>

    <div class="text-center">
      <button class="btn btn-radius-solid btn--shadow w-50 mt-2" id="finder-btn">Check!</button>
    </div>
  </ul>
</div>


<div class="result ResultA">
  <div class="ResultA__recommend">あなたにぴったりなのは・・・・</div>
  <div class="ResultA__Amenu">
    <div class="ResultA__Amenu__text">ラベンダー</div>
    <div class="ResultA__Amenu__detail">
      香りは繊細でフローラル。同時にウッディでもありくっきりとした輪郭があり、品の良さが感じられます。ラベンダーは体の不調にもよく使われ、そのマルチぶりはまさに<span>「万能薬」</span>です。<br>高いリラックス効果があるため、ストレスからくる<span>消化器系の症状</span>に役立つほか、高い血圧を下げて心臓の動きを落ち着かせる作用があります。<br><span>女性の体のトラブル全般</span>も守備範囲で生理不順を整えて生理痛を減らし、出産の苦痛を和らげると言います。
    </div>
    <div class="ResultA__Amenu__image"><%= image_tag 'lavender.jpg' ,class: "recommend_image" %></div>
    <%= render 'reload' %>
  </div>
</div>

<div class="result ResultB">
  <div class="ResultB__recommend">あなたにぴったりなのは・・・・</div>
  <div class="ResultB__Bmenu">
    <div class="ResultB__Bmenu__text">ローズマリー</div>
    <div class="ResultB__Bmenu__detail">
      精神を高揚させる働きがあります。<span>無気力や憂うつ</span>によく効きます。自分に自信がなく、強い自我に欠ける人が、自信をもち、自己実現に向けて行動できる強さを与えてくれます。<br>考えすぎをなくし、自分の能力に自信が持てるようになります。ローズマリーは心臓の拍動を強める働きがあります。そのため、<span>低血圧、手足の冷え</span>に効果的です。脳の血流量を増やすので、集中力をアップさせます。筋肉の強壮にもつながり、筋肉痛やこりにも効きます。<br>また、肌への作用は、特に頭皮の不調改善に優れます。白髪やフケの悩みにも有効です。<span>シャンプーに混ぜたり、オイルマッサージ</span>をお勧めします。
    </div>
    <div class="ResultB__Bmenu__image"><%= image_tag 'rosemary.jpg' ,class: "recommend_image" %></div>
    <%= render 'reload' %>
  </div>
</div>

<div class="result ResultC">
  <div class="ResultC__recommend">あなたにぴったりなのは・・・・</div>
  <div class="ResultC__Cmenu">
    <div class="ResultC__Cmenu__text">ゼラニウム</div>
    <div class="ResultC__Cmenu__detail">
      ローズに非常に似た香りがありますがローズの精油ほど高価ではないため昔から香水の原料として親しまれていました。ゼラニウムの得意技は<span>心身両面のバランスを取ること。</span>体に対してはホルモンや消化液皮脂の分泌を調節します。<br>女性にとっては生理前後の不快な症状を抑えるのに役立ちます。心に対する働きとしては、甘い香りが気分を明るくさせ不安を鎮める作用があります。最近では炎症を抑える効果があることが明らかになり、<span>トリートメントでリウマチや関節炎に使われることが増え</span>ています。
    </div>
    <div class="ResultC__Cmenu__image"><%= image_tag 'geranium.jpg' ,class: "recommend_image" %></div>
    <%= render 'reload' %>
  </div>
</div>

<div class="result ResultD">
  <div class="ResultD__recommend">あなたにぴったりなのは・・・・</div>
  <div class="ResultD__Dmenu">
    <div class="ResultD__Dmenu__text">スイートオレンジ</div>
    <div class="ResultD__Dmenu__detail">
      年齢や性別問わず幅広く好まれ比較的<span>シーンを選ばず</span>利用できます。子供が眠れない時や落ち着いて何かに取り組みたい時などに芳香剤やオイルトリートメントでこの香りを使うと効果バツグンです。血行を良くして体を温める効果もあるため<span>足浴にぴったり。</span>腸の動きの促して食欲を増進させるなど消化器官全般にも良く働きかけてくれます。
    </div>
    <div class="ResultD__Dmenu__image"><%= image_tag 'sweetorange.jpg' ,class: "recommend_image" %></div>
    <%= render 'reload' %>
  </div>
</div>

<div class="result ResultE">
  <div class="ResultE__recommend">あなたにぴったりなのは・・・・</div>
  <div class="ResultE__Emenu">
    <div class="ResultE__Emenu__text">ベルガモット</div>
    <div class="ResultE__Emenu__detail">
      ベルガモットの香りは少し複雑でシトラス系の中では個性的な部類です。爽やかなリモネンの香りの中に少し甘いフローラルな香りがするのはラベンダーにも含まれる酢酸リナリルを含むためです。さらに繊細なスパイシーさも感じられるため<span>リフレッシュとリラックスの両方の目的</span>で使うことができます。不安な気持ちを和らげ<span>自律神経の乱れからくる不眠</span>にも優しく作用します。
    </div>
    <div class="ResultE__Emenu__image"><%= image_tag 'bergamot.jpg' ,class: "recommend_image" %></div>
    <%= render 'reload' %>
  </div>
</div>

<div class="result ResultF">
  <div class="ResultF__recommend">あなたにぴったりなのは・・・・</div>
  <div class="ResultF__Fmenu">
    <div class="ResultF__Fmenu__text">イランイラン</div>
    <div class="ResultF__Fmenu__detail">
      特徴的なその名前の由来はタガログ語で「花の中の花」意味します。エキゾチックな香りが特徴であり心を開放的にし幸せな気分に導く<span>「フローラル・ハイ」</span>と呼ばれる体験をもたらす。日常を離れた世界へトリップするような陶酔感を与えてくれるためアジアのスパなどで良く使われています。イランイランは<span>副交感神経を優位</span>にし、血圧を下げる作用があります。そのため、高血圧やストレス性の不整脈、動悸の改善に効果が期待できます。実際に、イランイラン精油の<span>吸引</span>で、収縮期血圧の低下が認められたという研究報告もあります。
    </div>
    <div class="ResultF__Fmenu__image"><%= image_tag 'ilang-ilang.jpg' ,class: "recommend_image" %></div>
    <%= render 'reload' %>
  </div>
</div>

<div class="result ResultG">
  <div class="ResultG__recommend">あなたにぴったりなのは・・・・</div>
  <div class="ResultG__Gmenu">
    <div class="ResultG__Gmenu__text">カモミール</div>
    <div class="ResultG__Gmenu__detail">
      カモミールはヨーロッパ原産のハーブ。カモミールローマンとカモミールジャーマンが有名ですが、どちらも30センチほどの草丈で、羽毛を思わせるような葉を持ち、可愛らしい白い花をつけます。カモミールローマンは多年草で、カモミールジャーマンは一年草という違いがあります。<span>ハーブティーとして</span>は、カモミールジャーマンの方が多く飲まれており、カモミールローマンのハーブティーには若干苦味があります。精油の香りは、カモミールローマンはややフルーティーで酸味があり、カモミールジャーマンは濃厚な甘さがあります。カモミールはラベンダーとともに<span>リラックス効果の高い精油</span>として知られています。不安や緊張を和らげたり、心を落ち着けて安らかな夜を迎えるために、カモミールの香りは大いに役立ってくれます。
    </div>
    <div class="ResultG__Gmenu__image"><%= image_tag 'jasmine.jpg' ,class: "recommend_image" %></div>
    <%= render 'reload' %>
  </div>
</div>

<div class="result ResultH">
  <div class="ResultH__recommend">あなたにぴったりなのは・・・・</div>
  <div class="ResultH__Hmenu">
    <div class="ResultH__Hmenu__text">シナモン</div>
    <div class="ResultH__Hmenu__detail">
      気持ちを温めてくれる濃厚な香りのシナモンは中国では紀元前２７００年から記録が残っている歴史の古いハーブです。シナモンから作られたエッセンシャルオイルは、緊張をほぐして神経を落ち着かせ、心を元気づける作用や、<span>体を温める作用</span>があります。<span>抗菌作用</span>もあり、最近が心配な時や湿気の多い繁殖しやすい季節に散布するとその部屋は衛生的になります。
    </div>
    <div class="ResultH__Hmenu__image"><%= image_tag 'cinnamon.jpg' ,class: "recommend_image" %></div>
    <%= render 'reload' %>
  </div>
</div>

<div class="result ResultI">
  <div class="ResultI__recommend">あなたにぴったりなのは・・・・</div>
  <div class="ResultI__Imenu">
    <div class="ResultI__Imenu__text">ゆず</div>
    <div class="ResultI__Imenu__detail">
      寒さに強い柚子は、寒い時期にも温かく見守って希望を与えてくれるような精油です。シトラスの香りは、<span>希望やポジティブな考え</span>を与えてくれます。不安に悩むときや決断できない時に背中を押してくれます。また、<span>血行促進作用</span>があります。疲労回復にも効果的なため、柚子湯は疲れをとり元気を取り戻すのに最適です。免疫活性や自律神経のバランスを整えたりもしてくれます。肌へはあまり使用されませんが、殺菌作用や保湿作用が期待できます。
    </div>
    <div class="ResultI__Imenu__image"><%= image_tag 'yuzu.jpg' ,class: "recommend_image" %></div>
    <%= render 'reload' %>
  </div>
</div>

<div class="result ResultJ">
  <div class="ResultJ__recommend">あなたにぴったりなのは・・・・</div>
  <div class="ResultJ__Jmenu">
    <div class="ResultJ__Jmenu__text">フランキンセンス</<div>
      <div class="ResultJ__Jmenu__detail">
        中東が原産の常緑低木、薫香としても用いられるフランキンセンスは、リラックス効果が大変高い香りとして有名です。イライラとした心を鎮め、悲しい心をなぐさめ、心を穏やかにしてくれます。フランキンセンスは<span>瞑想</span>にも使われ、仕事や家事など忙しくて心に余裕がないときは、平常心を取り戻してくれます。呼吸をゆっくりにさせるので、平和な気持ちになるリラックス効果がある一方で、心を慰め、気持ちを高揚させる面もあります。鎮静と高揚。心を鎮静させながら、ゆっくりと強壮するというバランスのとれた効能で、<span>自分を取り戻したいときに使いたい精油</span>です。
      </div>
      <div class="ResultJ__Jmenu__image"><%= image_tag 'frankincense.jpg' ,class: "recommend_image" %></div>
      <%= render 'reload' %>
    </div>
  </div>
</div>

<hr class="my-3">
<div class='button-group'>
  <%= link_to "トップページへ", root_path, class:"btn btn-block" %>
</div>

app/views/home/index.html.erb
<%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="site-title">
  <h1>Aroma life</h1>
</div>

<div class="box">
  <div class="bgImg src1"></div>
  <div class="bgImg src2"></div>
  <div class="bgImg src3"></div>
  <div class="bgImg src4"></div>
  <div class="boxString">
    <p>「ストレスを感じる日常にアロマの癒しを」</p>
    <% if user_signed_in? %>
    <p>植物の香りは私たちの心と身体にやさしく働きかけます。<br>アロマテラピーを知ることは、自分の心や身体と向き合うこと。<br>正しい知識を得てアロマテラピーを生活に取り入れてみませんか。</p>
    <a href="#deck"><span></span></a>
    <% else %>
    <p>新規登録・ログインはこちらから</p>
    <div class="link-group">
      <%= link_to "sign up", new_user_registration_path, class:"btn-home" %>
      <%= link_to "log in", new_user_session_path, class:"btn-home" %>
    </div>
    <% end %>
  </div>
</div>


<div class="container text-center" id="works">
  <div class="card my-3">
    <h3 class="card-header bg-dark text-white">About Aroma life</h3>
    <div class="card-body">
      <h4 class="card-explain">Aroma lifeはアロマがもっと好きになるポータルサイトです！</h4>
      <p class="card-text">
        花の香り。フルーツの香り。森の香り。植物の香りは、私たちの心や身体にさまざまに働きかけます。アロマテラピーは、植物から抽出した香り成分である精油（エッセンシャルオイル）を使って、心身のトラブルを穏やかに回復し、健康や美容に役立てていく自然療法です。<br>Aroma
        lifeではアロマテラピーの楽しみ方、香りのバリエーションなど、いろいろな方の香りが好き！な気持ちが集めて<br>皆のアロマライフがちょっぴり豊かに広がるようなサイトを目指しています。あなたのお好みの香りを探したり<br>アロマの効果的な使い方を知って普段の生活にお役立てください。
      </p>
    </div>
  </div>

  <div class="contents-entry">
    <p>Main Contents</p>
  </div>

  <div class="deck-entry">
    <div id="deck" class="card-deck">
      <div class="card card-container bg-dark">
        <%= link_to diagnoses_path, class:"text-decoration-none" do %>
        <%= image_tag "finder-icon" ,class:"card-img-top" %>
        <div class="card-body text-white">
          <h5 class="card-title">Aroma Finder</h5>
          <p class="card-text">質問に答えてあなたにピッタリのアロマを見つけましょう</p>
        </div>
        <% end %>
      </div>

      <div class="card card-container bg-dark">
        <%= link_to posts_path, class:"text-decoration-none" do %>
        <%= image_tag "sns-icon" ,class:"card-img-top" %>
        <div class="card-body text-white">
          <h5 class="card-title">Everyone&apos;s Aroma</h5>
          <p class="card-text">あなたの癒しの時間をシェアしましょう</p>
        </div>
        <% end %>
      </div>

      <div class="card card-container bg-dark">
        <%= link_to tips_path, class:"text-decoration-none" do %>
        <%= image_tag "tips-icon" ,class:"card-img-top" %>
        <div class="card-body text-white">
          <h5 class="card-title">Tips</h5>
          <p class="card-text">生活に役立つアロマの豆知識を発信します</p>
        </div>
        <% end %>

      </div>
    </div>