config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "home#index"
  get "diagnoses", to: "home#diagnoses"
  get "users/show/:id" => "users#show"
  resources :tips, only: [:index, :show]

  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#new_guest"
  end
  resources :posts, except: [:update, :edit] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  mount_uploader :image, ImageUploader

  validates :title, presence: true,
                    length: { maximum: 30 }
  validates :aroma, presence: true, inclusion: { in: %w[フローラル ハーバル ウッディ シトラス 和の香り スパイシー エキゾチック その他] }
  validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[destroy]

  PER_PAGE = 5

  def index
    @posts = Post.includes([:user, :likes, :comments]).order(created_at: :desc).page(params[:page]).per(PER_PAGE)
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create!(post_params)
    @posts = Post.includes([:user, :likes, :comments]).order(created_at: :desc).page(params[:page]).per(PER_PAGE)
  end

  def destroy
    @post.destroy!
    @user = @post.user
    @posts = Post.includes([:user, :likes, :comments]).order(created_at: :desc).page(params[:page]).per(PER_PAGE)
    @my_posts = @user.posts.includes([:likes, :comments]).order(created_at: :desc).page(params[:page]).per(PER_PAGE)
    @like_posts = @user.like_posts.includes([:comments]).page(params[:page]).per(PER_PAGE)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :image, :aroma).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/views/posts/_modal.html.erb
<div class="modal-area">
  <button type="button" class="fixed_btn" data-toggle="modal" data-target="#exampleModal">
    <i class="far fa-comment-dots fa-2x"></i> 投稿する
  </button>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title font-weight-bold" id="exampleModalLabel">新規投稿</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>



      <%= form_for @post, remote: true do |f| %>
      <div class="modal-body font-weight-bold">
        <div class="form-group">
          <%= f.label :title, "タイトル(30字以内)" %>
          <%= f.text_field :title, class:"form-control",required: true ,maxlength:"30" %>
        </div>

        <div class="form-group">
          <%= f.label :title, "香りのタイプ" %>
          <div class="d-flex">
            <%= f.select :aroma, [["フローラル", "フローラル"], ["ハーバル", "ハーバル"], ["ウッディ", "ウッディ"],["シトラス", "シトラス"],["和の香り", "和の香り"],["スパイシー", "スパイシー"],["エキゾチック", "エキゾチック"],["その他", "その他"]],{ :include_blank => "選択(必須)▼" },:required => true, :id =>"aromaselector" %>

            <div class="result ml-2 font-weight-bold">
              <div id="フローラル" class="aromas フローラル">甘く華やかな香りが特徴の癒やし系</div>
              <div id="ハーバル" class="aromas ハーバル"> 少し薬草の香りがするスッキリ系</div>
              <div id="ウッディ" class="aromas ウッディ"> 森にも似た落ち着く香りの安定系</div>
              <div id="シトラス" class="aromas シトラス"> 爽やかな香りが弾ける元気系</div>
              <div id="和の香り" class="aromas 和の香り"> どこか懐かしい香りのするほっこり系</div>
              <div id="スパイシー" class="aromas スパイシー"> インパクト強めで刺激的な個性系</div>
              <div id="エキゾチック" class="aromas エキゾチック"> オリエンタルで個性的な官能系</div>
            </div>

          </div>
        </div>

        <div class="form-group">
          <%= f.label :content, "本文" %>
          <%= f.text_area :content, class:"form-control form-content",required: true %>
        </div>

        <div class="form-group">
          <%= f.label :image,"画像"%><br>
          <%= f.file_field :image, accept: "image/png,image/jpeg,image/gif" %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        <%= f.submit "投稿する", class:"btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(function () {
    $('.aromas').hide();
    $('#aromaselector').change(function () {
      $('.aromas').hide();
      $('#' + $(this).val()).show();
    });
  });
</script>

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
<div class="card mb-1" id="post-<%= post.id%>">
  <%= link_to post do %>
  <div class="card-body">
    <div class="icon_space">
      <% if post.user.image? %>
      <img src=<%= post.user.image %> class="icon_image">
      <% else %>
      <%= image_tag 'profile_default2.jpg' ,class: "icon_image" %>
      <% end %>
    </div>

    <div class='text_space'>
      <p class='card-text'><%= post.title %></p>
      <p class='<%= translation_class_name(post.aroma) %> badge badge-pill'><%= post.aroma %></p>
      <p class='text_content'><%= post.content %></p>
    </div>

    <div class='thumbnail_space'>
      <div class="like_space">
        <i class="far fa-comment-dots home-icon"></i> <%= post.comments.length %>
        <i class="fas fa-heart home-icon"></i> <%= post.likes.length %>
      </div>
      <% if post.image? %>
      <%= image_tag post.image.thumb.url ,class: 'thumb-image'%>
      <% else %>
      <%= image_tag 'noimage.png',class: 'noimage' %>
      <% end %>
    </div>
  </div>
  <% end %>

  <span class="text-muted pl-2 d-inline-flex icons">
    <i class='fas fa-clock home-icon mr-1'></i> <%= time_ago_in_words(post.created_at) %>前
    <% if post.user == current_user %>
    <%= link_to post_path(post),class: 'text-danger', method: :delete, data: { confirm: '削除しますか?', remote: true } do %>
    <i class="fas fa-trash home-icon ml-2"></i> 削除
    <% end %>
    <% end %>
  </span>
</div>
<% end %>

<%= paginate posts %>

app/views/posts/_side-bar.html.erb
<div class="panel">
  <div class="panel-heading">
    <div class="user-panel text-center">
      <span class="icon_image">
        <% if current_user.image? %>
        <img src=<%= current_user.image %> class="icon_image_side">
        <% else %>
        <%= image_tag 'profile_default2.jpg' ,class: "icon_image_side" %>
        <% end %>
      </span>
      <div class="user_name_side">
        <p class="my-2">
          <%= current_user.name %>
        </p>
      </div>
    </div>

    <div class="panel-body text-center">
      <div data-toggle="tooltip">
        <a class="show-btn-link" href="/users/show/<%= current_user.id %>">
          <i class="fas fa-chalkboard-teacher home-icon "></i><br>マイページ</a>
      </div>
    </div>

  </div>

app/views/posts/_tabs.html.erb
<div class="tabs">
  <input id="all" type="radio" name="tab_item" checked>
  <label class="tab_item" for="all">投稿した記事</label>

  <input id="like" type="radio" name="tab_item">
  <label class="tab_item" for="like">いいねした記事</label>

  <div class="tab_content" id="all_content">
    <%= render 'posts/posts' , posts: @posts %>
  </div>

  <div class="tab_content" id="like_content">
    <%= render 'posts/posts' , posts: @like_posts %>
  </div>
</div>

app/views/posts/create.js.erb
$("textarea").val("");
$("input").val("");
$("select").val("");
$('#exampleModal').modal('hide')
$('.result').hide();
$('.posts').html("<%= escape_javascript(render 'posts', posts: @posts) %>")

app/views/posts/destroy.js.erb
$('.posts').html("<%= escape_javascript(render 'posts', posts: @posts) %>")
$('#all_content').html("<%= escape_javascript(render 'posts', posts: @my_posts) %>")
$('#like_content').html("<%= escape_javascript(render 'posts', posts: @like_posts) %>")

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'posts', media: 'all', 'data-turbolinks-track': 'reload' %>
<div id="wrapper" class='big-bg'>
  <div class="post-content ">
    <h2 class='page-title'>everyone&apos;s aroma</h2>
    <p>癒やしの時間をシェアしませんか？</p>
  </div>
</div>

<div class="content-entry">
  <p>Posts list</p>
</div>

<div class="container mt-4">

  <div class='main-contents'>
    <div class="posts">
      <%= render 'posts', posts: @posts %>
    </div>
    <aside>
      <%= render 'side-bar' %>
    </aside>
  </div>

  <%= render 'modal' %>

  <hr class="my-3">

  <div class=button-group>
    <%= link_to "トップページへ", root_path, class:"btn btn-block" %>
  </div>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'posts', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="post_info">
    <div class="user_info">
        <a href="/users/show/<%= @post.user.id %>">
            <% if @post.user.image? %>
            <img src=<%= @post.user.image %> class="icon_image_side">
            <% else %>
            <%= image_tag 'profile_default2.jpg' ,class: "icon_image_side" %>
            <% end %>
            <div class="user_name">
                <p><%= @user.name %></p>
            </div>
        </a>
    </div>

    <div class='post_entry'>
        <h2 class="post_title"><%= @post.title %></h2>
        <p class='<%= translation_class_name(@post.aroma) %> badge badge-pill'><%= @post.aroma %></p>
    </div>

</div>

<div class="post-article">
    <p><%= text_url_to_link(@post.content).html_safe %></p>
</div>

<div class="post_img_full mt-5">
    <% if @post.image? then %>
    <%= image_tag @post.image.url ,class: 'full_image'%>
    <% end %>
</div>

<div class='like_to_post'>
    <p class="like_lead">この投稿が気に入ったらいいねをしてみよう！</p>
    <div id="likes_buttons<%= @post.id %>">
        <%= render partial: 'likes/like', locals: { post: @post, like: @like} %>
    </div>
</div>

<div class="comment-create my-5">
    <h3 class="text-center">コメントをする</h3>
    <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
</div>

<div id="comments_area">
    <%= render partial: 'comments/index', locals: { comments: @comments } %>
</div>

<hr class="my-3">

<div class=button-group>
    <%= link_to "投稿一覧へ", posts_path, class:"btn btn-block" %>
    <%= link_to "トップページへ", root_path, class:"btn btn-block" %>
</div>